id: P65967E45
initial_creation_type: input
source_metadata:
  title: Buddha Śākyamuni
  language: es
  description: 'Texts by and about Buddha Śākyamuni (shākya thub pa):'
  volume:
    687c027a085644ce9a3061d97cfb5454:
      title: Guru Yoga of the Guru Mahāmuni
      parent: Guru Yoga
    080a183af9584502a6ef3eb5350ce95e:
      title: 'The Merry Sea of Blessings: A Guru Yoga of the Lord of Sages, Peerless
        Teacher of All, Including the Devas'
      parent: Guru Yoga
    c55a8539bf76421ea08620196192ed94:
      title: In Praise of the Twelve Deeds of the Buddha
      parent: Praise
    53a70827cd7f4ae583005fe756809db7:
      title: 'Praise of the Buddha: With Skilful Means & Compassion...'
      parent: Praise
    edb721e9f5b64ca7a2b84f44eaa76842:
      title: Praise of the Twelve Acts of the Buddha
      parent: Praise
    9577a9b427be41a28a4519452da329f9:
      title: Short Praise of the Buddha's Deeds
      parent: Praise
    9234cf67668a4e34981a78b979d35675:
      title: Supplication to Lord Buddha together with the Sixteen Arhats
      parent: Prayers
    a8a6fdba06de4d9baba07d45b741951d:
      title: Verses on the Buddha's Previous Lives
      parent: Prayers
    c89f555ca1614b5fb1e82da3fea84151:
      title: 'The Treasury of Blessings: A Practice of Buddha Śākyamuni'
      parent: Prayers to Śākyamuni
created_at: '2022-03-01T02:12:34.856227'
last_modified_at: '2022-03-01T02:12:34.856230'
